Added monte carlo ablation and fixed a few minor things

diff --git a/coupled_network/makefile b/coupled_network/makefile
--- a/coupled_network/makefile
+++ b/coupled_network/makefile
@@ -3,7 +3,7 @@ DATASET_cifar10 := cifar10
 DATASET_svhn := svhn
 DATASET_all := cifar10_svhn
 
-.PHONY: precompute figure-cdf-all-measures
+.PHONY: precompute figure-cdf-all-measures figure-triangle-cdf figure-supp-envs-vs-miness
 
 
 # Produce the same figures as in the paper
@@ -11,31 +11,35 @@ paper:
 	@echo "Building paper figures:"
 
 	@echo "... Figure 1"
-	@make figure-cdf-all-measures dataset=all min_weight=12 filter_noise=True
+	@make figure-cdf-all-measures dataset=all min_ess=12 filter_noise=True
 	@mv figure__signerror_cdf_per_hp__ds_cifar10_svhn__mess_12.000000__filternoise_True_cdf_per_hp.pdf figure_1.pdf
 
 	@echo "... Figure 2"
-	@make figure-triangle-cdf dataset=all measure=complexity.pacbayes_mag_flatness hp=hp.model_depth min_weight=12 filter_noise=True
+	@make figure-triangle-cdf dataset=all measure=complexity.pacbayes_mag_flatness hp=hp.model_depth min_ess=12 filter_noise=True
 	@mv figure_triangle_cdf__ds_cifar10_svhn__mess_12.000000__gm_pacbayes.mag.flatness__filternoise_True_hp_hp.model_depth.pdf figure_2.pdf
 
 	@echo "... Figure 3"
 	@make figure-supp-envs-vs-miness dataset=all
 	@mv figure_miness_remaining_environments_ds_cifar10_svhn_range_0_100.pdf figure_3.pdf
 
+	@echo "... Figure 4"
+	@make figure-supp-monte-carlo-ablation dataset=all min_ess=12  
+	@ls figure_monte_carlo_noise_ablation__*__ds_cifar10_svhn__mess_12.000000_cdf.pdf | cut -d'_' -f7 | xargs -I{} mv figure_monte_carlo_noise_ablation__{}__ds_cifar10_svhn__mess_12.000000_cdf.pdf figure_4_{}.pdf
+
 	@echo "... Figure 8"
-	@make figure-cdf-all-measures dataset=svhn min_weight=12 filter_noise=True
+	@make figure-cdf-all-measures dataset=svhn min_ess=12 filter_noise=True
 	@mv figure__signerror_cdf_per_hp__ds_svhn__mess_12.000000__filternoise_True_cdf_per_hp.pdf figure_8.pdf
 
 	@echo "... Figure 9a"
-	@make figure-triangle-cdf dataset=svhn measure=complexity.pacbayes_orig hp=hp.model_depth min_weight=12 filter_noise=True
+	@make figure-triangle-cdf dataset=svhn measure=complexity.pacbayes_orig hp=hp.model_depth min_ess=12 filter_noise=True
 	@mv figure_triangle_cdf__ds_svhn__mess_12.000000__gm_pacbayes.orig__filternoise_True_hp_hp.model_depth.pdf figure_9a.pdf
 
 	@echo "... Figure 9b"
-	@make figure-triangle-cdf dataset=svhn measure=complexity.pacbayes_orig hp=hp.model_width min_weight=12 filter_noise=True
+	@make figure-triangle-cdf dataset=svhn measure=complexity.pacbayes_orig hp=hp.model_width min_ess=12 filter_noise=True
 	@mv figure_triangle_cdf__ds_svhn__mess_12.000000__gm_pacbayes.orig__filternoise_True_hp_hp.model_width.pdf figure_9b.pdf
 
 	@echo "... Figure 10"
-	@make figure-cdf-all-measures dataset=cifar10 min_weight=12 filter_noise=True
+	@make figure-cdf-all-measures dataset=cifar10 min_ess=12 filter_noise=True
 	@mv figure__signerror_cdf_per_hp__ds_cifar10__mess_12.000000__filternoise_True_cdf_per_hp.pdf figure_10.pdf
 
 
@@ -50,14 +54,14 @@ precompute: .require_dataset .require_filter_noise
 
 # Main text figure: CDF of all environment sign errors per HP
 figure-cdf-all-measures: precompute
-figure-cdf-all-measures: .require_dataset .require_min_weight .require_filter_noise
-	python3 figure_cdf_all_measures.py $(DATASET_$(dataset)) $(min_weight) $(filter_noise)
+figure-cdf-all-measures: .require_dataset .require_min_ess .require_filter_noise
+	python3 figure_cdf_all_measures.py $(DATASET_$(dataset)) $(min_ess) $(filter_noise)
 
 
 # Main text figure: CDF of environment sign errors for pairs of HP values
 figure-triangle-cdf: precompute
-figure-triangle-cdf: .require_dataset .require_measure .require_hp .require_min_weight .require_filter_noise
-	python3 figure_triangle_cdf.py $(DATASET_$(dataset)) $(measure) $(hp) $(min_weight) $(filter_noise)
+figure-triangle-cdf: .require_dataset .require_measure .require_hp .require_min_ess .require_filter_noise
+	python3 figure_triangle_cdf.py $(DATASET_$(dataset)) $(measure) $(hp) $(min_ess) $(filter_noise)
 
 
 # Supplementary Figure: number of environments remaining at various min effective sample sizes
@@ -65,6 +69,19 @@ figure-supp-envs-vs-miness: lower = 0
 figure-supp-envs-vs-miness: upper=100
 figure-supp-envs-vs-miness: .require_dataset
 	python supp_figure_envs_remaining.py $(DATASET_$(dataset)) $(lower) $(upper)
+
+
+# Ablation study of Monte Carlo noise filtering
+figure-supp-monte-carlo-ablation: .require_dataset .require_min_ess
+	@test ! -f environment_cache/precomputations__filternoisetrue__$(DATASET_$(dataset)).pkl && \
+		echo "Precomputation file not found (with noise filtering). Precomputing..." && \
+		python3 supp_figure_monte_carlo_ablation.py $(DATASET_$(dataset)) true \
+	|| echo "Precomputation file found (with noise filtering)."
+	@test ! -f environment_cache/precomputations__filternoisefalse__$(DATASET_$(dataset)).pkl && \
+		echo "Precomputation file not found (without noise filtering). Precomputing..." && \
+		python3 create_environments.py $(DATASET_$(dataset)) false \
+	|| echo "Precomputation file found (without noise filtering)."
+	python supp_figure_monte_carlo_ablation.py $(DATASET_$(dataset))  $(min_ess)
 
 
 .require_dataset:
@@ -85,10 +102,11 @@ ifndef measure
 endif
 
 
-.require_min_weight:
-ifndef min_weight
-	$(error min_weight parameter is required. This is the minimum sum of Hoeffding weights in an environment for it to be considered in the analysis. Add min_weight=<value> to your command.)
+.require_min_ess:
+ifndef min_ess
+	$(error min_ess parameter is required. This is the minimum effective sample size in an environment for it to be considered in the analysis. Add min_ess=<value> to your command.)
 endif
+
 
 .require_filter_noise:
 ifndef filter_noise
